"use client"

import { useCallback, useState } from "react"
import { usePathname } from "next/navigation"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Spinner } from "@/components/ui/spinner"
import { useStudentGrades, useStudentTranscript } from "@/hooks/use-student-portal"
import { downloadStudentTranscriptCsv, downloadStudentTranscriptPdf } from "@/lib/students-api"
import { StudentFeatureGate } from "@/components/student-feature-gate"

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement("a")
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

export default function StudentGradesPage() {
  const pathname = usePathname()
  const isTranscriptPage = Boolean(pathname && pathname.includes("/student/transcript"))
  const { grades, isLoading: gradesLoading, error: gradesError } = useStudentGrades()
  const { transcript, isLoading: transcriptLoading, error: transcriptError } = useStudentTranscript()
  const [downloading, setDownloading] = useState<null | "csv" | "pdf">(null)
  const [downloadError, setDownloadError] = useState<string | null>(null)

  const handleDownloadTranscriptPdf = useCallback(async () => {
    try {
      setDownloadError(null)
      setDownloading("pdf")
      const blob = await downloadStudentTranscriptPdf()
      saveBlob(blob, `transcript-${new Date().toISOString().slice(0, 10)}.pdf`)
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : "Unable to download transcript PDF")
    } finally {
      setDownloading(null)
    }
  }, [])

  const handleDownloadTranscriptCsv = useCallback(async () => {
    try {
      setDownloadError(null)
      setDownloading("csv")
      const blob = await downloadStudentTranscriptCsv()
      saveBlob(blob, `transcript-${new Date().toISOString().slice(0, 10)}.csv`)
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : "Unable to download transcript CSV")
    } finally {
      setDownloading(null)
    }
  }, [])

  const fmt = (val: unknown) => (val === null || val === undefined || val === "" ? "—" : `${val}`)
  const transcriptRows = transcript?.semesters.flatMap((semester) =>
    semester.courses.map((course) => ({
      ...course,
      semester: semester.semester,
      semesterGpa: semester.gpa,
    })),
  ) ?? []

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <p className="text-sm text-muted-foreground">{isTranscriptPage ? "Transcript" : "Grades"}</p>
          <h1 className="text-2xl font-bold text-foreground">
            {isTranscriptPage ? "Academic transcript" : "Course grades"}
          </h1>
          <p className="text-sm text-muted-foreground">
            {isTranscriptPage
              ? "Finalized grades only, with GPA and secure export generated by the backend."
              : "Breakdown of midterm, project, final, participation, and totals."}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="border-border text-foreground">
            {isTranscriptPage ? `${transcript?.semesters.length ?? 0} semesters` : `${grades.length} courses`}
          </Badge>
          {isTranscriptPage && (
            <StudentFeatureGate featureKey="transcript-export">
              <Button size="sm" variant="outline" onClick={handleDownloadTranscriptPdf} disabled={downloading !== null}>
                {downloading === "pdf" ? "Downloading PDF..." : "Download PDF"}
              </Button>
              <Button size="sm" variant="outline" onClick={handleDownloadTranscriptCsv} disabled={downloading !== null}>
                {downloading === "csv" ? "Downloading CSV..." : "Download CSV"}
              </Button>
            </StudentFeatureGate>
          )}
        </div>
      </div>

      {(gradesError || transcriptError || downloadError) && (
        <Alert variant="destructive">
          <AlertTitle>{isTranscriptPage ? "Unable to load transcript" : "Unable to load grades"}</AlertTitle>
          <AlertDescription>{transcriptError || gradesError || downloadError}</AlertDescription>
        </Alert>
      )}

      {isTranscriptPage ? (
        transcriptLoading && !transcript ? (
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Spinner className="h-4 w-4" /> Loading transcript
          </div>
        ) : !transcript || transcriptRows.length === 0 ? (
          <Card className="border border-border bg-card">
            <CardContent className="py-5 text-sm text-muted-foreground">
              No finalized transcript records are available yet.
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            <Card className="border border-border bg-card">
              <CardContent className="grid gap-3 py-5 md:grid-cols-3">
                <div>
                  <div className="text-xs uppercase tracking-[0.08em] text-muted-foreground">Student</div>
                  <div className="font-semibold text-foreground">
                    {transcript.student.firstName} {transcript.student.lastName}
                  </div>
                  <div className="text-sm text-muted-foreground">{transcript.student.displayId}</div>
                </div>
                <div>
                  <div className="text-xs uppercase tracking-[0.08em] text-muted-foreground">Program</div>
                  <div className="font-semibold text-foreground">{transcript.student.program || "—"}</div>
                </div>
                <div>
                  <div className="text-xs uppercase tracking-[0.08em] text-muted-foreground">CGPA</div>
                  <div className="font-semibold text-foreground">{transcript.cumulativeGpa.toFixed(2)}</div>
                  <div className="text-sm text-muted-foreground">{transcript.cumulativeCredits} credits</div>
                </div>
              </CardContent>
            </Card>

            <Card className="border border-border bg-card">
              <CardContent className="p-0">
                <div className="overflow-x-auto">
                  <table className="min-w-full text-sm">
                    <thead className="bg-muted/60 text-muted-foreground text-xs uppercase tracking-[0.08em]">
                      <tr>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Semester</th>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Course</th>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Credits</th>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Campus</th>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Grade</th>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Letter</th>
                        <th className="px-4 py-3 text-left font-semibold text-foreground">Semester GPA</th>
                      </tr>
                    </thead>
                    <tbody>
                      {transcriptRows.map((row) => (
                        <tr key={row.enrollmentId} className="border-t border-border/60 hover:bg-secondary/30">
                          <td className="px-4 py-3 text-foreground">{row.semester}</td>
                          <td className="px-4 py-3">
                            <div className="font-semibold text-foreground">{row.courseTitle}</div>
                            <div className="text-xs text-muted-foreground">{row.courseCode}</div>
                          </td>
                          <td className="px-4 py-3 text-foreground">{row.credits}</td>
                          <td className="px-4 py-3 text-foreground">{row.campus ?? "—"}</td>
                          <td className="px-4 py-3 text-foreground">{fmt(row.gradeTotal ?? row.grade)}</td>
                          <td className="px-4 py-3 text-foreground">{fmt(row.letterGrade)}</td>
                          <td className="px-4 py-3 text-foreground">{row.semesterGpa.toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </div>
        )
      ) : gradesLoading && grades.length === 0 ? (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Spinner className="h-4 w-4" /> Loading grades
        </div>
      ) : grades.length === 0 ? (
        <Card className="border border-border bg-card">
          <CardContent className="py-5 text-sm text-muted-foreground">No grades available yet.</CardContent>
        </Card>
      ) : (
        <Card className="border border-border bg-card">
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead className="bg-muted/60 text-muted-foreground text-xs uppercase tracking-[0.08em]">
                  <tr>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Course</th>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Midterm</th>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Project</th>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Final</th>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Participation</th>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Total</th>
                    <th className="px-4 py-3 text-left font-semibold text-foreground">Letter</th>
                  </tr>
                </thead>
                <tbody>
                  {grades.map((enrollment) => {
                    const letter =
                      enrollment.letterGrade ??
                      (enrollment.gradeTotal !== null && enrollment.gradeTotal !== undefined
                        ? `${enrollment.gradeTotal}%`
                        : "In progress")
                    return (
                      <tr key={enrollment.id} className="border-t border-border/60 hover:bg-secondary/30">
                        <td className="px-4 py-3">
                          <div className="font-semibold text-foreground">{enrollment.courseTitle}</div>
                          <div className="text-xs text-muted-foreground">
                            {enrollment.courseCode ?? enrollment.displayId ?? enrollment.courseId}
                          </div>
                        </td>
                        <td className="px-4 py-3 text-foreground">{fmt(enrollment.gradeMidterm)}</td>
                        <td className="px-4 py-3 text-foreground">{fmt(enrollment.gradeProject)}</td>
                        <td className="px-4 py-3 text-foreground">{fmt(enrollment.gradeFinal)}</td>
                        <td className="px-4 py-3 text-foreground">{fmt(enrollment.gradeParticipation)}</td>
                        <td className="px-4 py-3 text-foreground">{fmt(enrollment.gradeTotal)}</td>
                        <td className="px-4 py-3">
                          <Badge variant="outline" className="border-border text-foreground">
                            {letter}
                          </Badge>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
